<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Fri Feb 01 2019 07:54:11 GMT+0000 (UTC)). */
return array(
	'public/dist/rml_gutenberg.js' => 'b62563b3ea3b0c6f0c4e91ce35e2ae2e',
	'public/dist/rml_shortcode.js' => 'e42c794b607ed6eecbd456f2dc17990a',
	'public/dist/rml.js' => 'd5c0a054499cb2fa533fcd79252328a1',
	'public/dist/rml.css' => '75f088fffeba10f9394493135aec9b42',
	'public/dev/rml_gutenberg.js' => '643070ad14921fcf9ee6aec7665a7e82',
	'public/dev/rml_shortcode.js' => 'a122c76fd7b52f5f53604b0ddc0548fc',
	'public/dev/rml.js' => '7982432b7638eb3d18b65cb21d15366f',
	'public/dev/rml.css' => '8b01d58a5e307be1a68704f094aed381',
);
